### ISSUE TITLE
Tow Vehicles Falling Through Floor

### ISSUE THREAD

**Issue by DannysRP** [WaypointRP/wp-tow-hauling#1]
When I attach a vehicle to the town vehicle via the /tow command the tow vehicle falls through the floor and I can no longer /untow the vehicle. I've tried this on multiple different vehicles and have had the same result.

When trying to /tow objects it locks the vehicle in place and I can no longer drive said vehicle.

I am running the QBCore framework and this is a fresh install of the resource.

![1](https://github.com/WaypointRP/wp-tow-hauling/assets/88177315/67e257b3-2a7a-4d14-b92d-b4bc2acbadf8)

**Comment by BackSH00TER** [comment]
@DannysRP From the looks of it based on your picture, you are likely selecting the vehicles in the wrong order. Make sure to follow the prompts, first select the actual tow vehicle, then second you select the vehicle you are trying to tow. 

From the picture it looks like the towtruck gets "towed" by the car, which would explain it partially falling through the world.

**Comment by DannysRP** [comment]
@BackSH00TER Okay I will test that and see if that's the case. Pick the tow vehicle first, then the towing object second.
