### ISSUE TITLE
ox_lib notifications not working.

### ISSUE THREAD

**Issue by KevinL852** [WaypointRP/wp-tow-hauling#2]
When the `Config.Notify` is set to 'ox' I get the following error:
`SCRIPT ERROR: @wp-tow-hauling/shared/framework.lua:40: attempt to index a nil value (global 'lib')^7`

I tried adding `lib = exports['ox_lib']` which got rid of the error but resulted in this:
`Uncaught TypeError: Cannot read properties of undefined (reading 'title') (@ox_lib/web/build/assets/index-0iYzIDK5.js:1015)`

The script still works, just don't get any notifications.
I'm not using any framework and ox_lib is present on the server. Any help would be appreciated.

**Comment by BackSH00TER** [comment]
You need to uncomment this line in the fxmanifest
-- '@ox_lib/init.lua', -- Uncomment this if you are planning to use any ox scripts (such as ox notify)

**Comment by KevinL852** [comment]
Completely overlooked this, oops...
Works fine now, thanks.
